# unbind default alt+arrow behaviors
keybind = alt+left=unbind
keybind = alt+right=unbind
keybind = alt+up=unbind
keybind = alt+down=unbind

# Tmux pane navigation with Alt+arrows (Ctrl+B is tmux prefix \x02)
keybind = alt+left=text:\x02\x68
keybind = alt+right=text:\x02\x6c
keybind = alt+up=text:\x02\x6b
keybind = alt+down=text:\x02\x6a

# Cycle through panes with Alt+Tab (Ctrl+B + o)
keybind = alt+tab=text:\x02\x6f

# Ghostty native pane navigation with Ctrl+Shift+arrows
keybind = ctrl+shift+left=goto_split:left
keybind = ctrl+shift+right=goto_split:right
keybind = ctrl+shift+up=goto_split:up
keybind = ctrl+shift+down=goto_split:down

# Close Ghostty native pane on Cmd+Shift+w
keybind = super+shift+w=close_surface

# Open ghostty quick terminal on Cmd+f
keybind = cmd+f=toggle_quick_terminal

# Go to the N window in tmux in tmux it is Ctrl+b+number
keybind = super+one=text:\x02\x31
keybind = super+two=text:\x02\x32
keybind = super+three=text:\x02\x33
keybind = super+four=text:\x02\x34
keybind = super+five=text:\x02\x35
keybind = super+six=text:\x02\x36
keybind = super+seven=text:\x02\x37
keybind = super+eight=text:\x02\x38
keybind = super+nine=text:\x02\x39

# New tmux window on Cmd+t in tmux it is Ctrl+b+c
keybind = super+t=text:\x02\x63

# Close tmux pane on Cmd+w in tmux it is Ctrl+b+x (it is using a custom keybind in tmux to kill the pane)
keybind = super+w=text:\x02\x78

# Go to the left tab on Cmd+[ in tmux it is Ctrl+b+p
keybind = super+left_bracket=text:\x02\x70

# Go to the right tab on Cmd+] in tmux it is Ctrl+b+n
keybind = super+right_bracket=text:\x02\x6e

# Go to the last tab on Cmd+l in tmux it is Ctrl+b+l
keybind = super+l=text:\x02\x6c

# Open window list panel on Cmd+` in tmux it is Ctrl+b+w
keybind = super+grave_accent=text:\x02\x77

# Split Window Horizontally on Cmd+\ in tmux it is Ctrl+b+"
keybind = super+backslash=text:\x02\x22

# Split Window Vertically on Cmd+| in tmux it is Ctrl+b+%
keybind = super+shift+backslash=text:\x02\x25

# Go to copy mode on Cmd+u in tmux it is Ctrl+b+[
keybind = super+u=text:\x02\x5b

# Resize-pane -Z on Cmd+z in tmux it is Ctrl+b+z
keybind = super+z=text:\x02\x7a
